# Model arguments
# 指向SFT训练后的REF teacher模型
model_name_or_path: /home/yunbokun/ADPA/data/mistral-7b-deita/ref_teacher
torch_dtype: bfloat16

# Data training arguments
# 修改为你的偏好对齐数据集路径
# 如果数据集在HuggingFace Hub上，使用格式: argilla/dpo-mix-7k
# 如果是本地数据集，使用绝对路径
dataset_mixer:
  "/home/yunbokun/Datasets/preference alignment/dpo-mix-7k": 1.0
dataset_splits:
- train
preprocessing_num_workers: 12
overwrite_output_dir: false

# DPOTrainer arguments
bf16: true
do_eval: false
# 2张显卡，调整gradient_accumulation_steps以保持有效batch size
# 原配置: per_device_batch_size=1, gradient_accumulation=16, 8卡 -> 有效batch=128
# 2卡配置: per_device_batch_size=1, gradient_accumulation=64 -> 有效batch=128
gradient_accumulation_steps: 64
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
learning_rate: 5.0e-7
log_level: info
logging_steps: 1
lr_scheduler_type: cosine
max_length: 2048
max_prompt_length: 1800
num_train_epochs: 1
optim: adamw_torch
# 修改为你的输出目录
output_dir: /home/yunbokun/ADPA/data/mistral-7b-deita/dpo_teacher
per_device_train_batch_size: 1
push_to_hub: false
save_strategy: "steps"
save_steps: 100
save_only_model: true
seed: 42
warmup_ratio: 0.1
dataset_num_proc: 64
beta: 0.01

# DPO配置
sft_on_chosen: 0
dpo_weight: 1
distillation_weight: 0
chosen_distil_weight: 0
rejected_distil_weight: 0
adpa_weight: 0
